//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWebApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int Номер_записи { get; set; }
        public int Номер_приема { get; set; }
        public int Номер_карты { get; set; }
        public int Код_сотрудника { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Reception Reception { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
